#!/usr/bin/env python3
"""Build a single-file TinyLib amalgamation."""

from __future__ import annotations

import argparse
from pathlib import Path
import re


LOCAL_INCLUDE_RE = re.compile(r'^\s*#\s*include\s+"([^"]+)"\s*$')


def bundle_file(path: Path, root: Path, seen: set[Path], stack: list[Path]) -> str:
    path = path.resolve()
    if path in seen:
        rel = path.relative_to(root)
        return f"/* skipped duplicate tinylib include: {rel} */\n"

    if path in stack:
        cycle = " -> ".join(str(p.relative_to(root)) for p in stack + [path])
        raise RuntimeError(f"local include cycle: {cycle}")

    seen.add(path)
    stack.append(path)

    rel = path.relative_to(root)
    out: list[str] = [
        f"\n/* begin tinylib file: {rel} */\n",
    ]

    for line in path.read_text(encoding="utf-8").splitlines(keepends=True):
        match = LOCAL_INCLUDE_RE.match(line)
        if not match:
            out.append(line)
            continue

        include_name = match.group(1)
        include_path = (path.parent / include_name).resolve()
        try:
            include_path.relative_to(root)
        except ValueError:
            out.append(line)
            continue

        if not include_path.exists():
            raise FileNotFoundError(f"{rel}: missing local include {include_name}")

        out.append(bundle_file(include_path, root, seen, stack))

    out.append(f"\n/* end tinylib file: {rel} */\n")
    stack.pop()
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path("include/tinylib"),
        help="TinyLib source folder to bundle",
    )
    parser.add_argument(
        "--entry",
        default="tinylib.c",
        help="Entry file relative to --root",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("target/tinylib.c"),
        help="Output amalgamation path",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    entry = (root / args.entry).resolve()
    output = args.output

    text = "/* This file is generated by tools/bundle.py. */\n"
    text += "/* Include or compile it in exactly one translation unit. */\n"
    text += bundle_file(entry, root, set(), [])

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
